src/CoollabTech.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoollabTech.UI.Web.Models;
using CoollabTech.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using CoollabTech.Application.ViewModels;

namespace CoollabTech.UI.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICitizenAppService _citizenAppService;

        public HomeController(ILogger<HomeController> logger, ICitizenAppService citizenAppService)
        {
            _logger = logger;
            _citizenAppService = citizenAppService;
            
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            return View(_citizenAppService.GetAll());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        [Route("edit-citizen/{id:guid}")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var citizenViewModel = _citizenAppService.GetById(id.Value);

            if (citizenViewModel == null)
            {
                return NotFound();
            }

            return View(citizenViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit-citizen/{id:guid}")]
        public IActionResult Edit(CitizenViewModel citizenViewModel)
        {
            if (!ModelState.IsValid) return View(citizenViewModel);

            var citizen = new CitizenViewModel
            {
                Id = citizenViewModel.Id,
                Name = citizenViewModel.Name,
                NickName = citizenViewModel.NickName,
                Document = citizenViewModel.Document,
                Email = citizenViewModel.Email,
                Gender = citizenViewModel.Gender,
                Excluded = false,
                Active = true
            };

            _citizenAppService.Update(citizen);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/CoollabTech.UI.Web/Controllers/TicketController.cs
using CoollabTech.Application.Interfaces;
using CoollabTech.Application.ViewModels;
using CoollabTech.Domain.Tickets;
using CoollabTech.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq.Expressions;

namespace CoollabTech.UI.Web.Controllers
{
    public class TicketController : Controller
    {
        private readonly ILogger<TicketController> _logger;
        private readonly ITicketAppService _ticketAppService;
        private readonly ITicketStatusAppService _ticketStatusAppService;
        private readonly ITicketTypeAppService _ticketTypeAppService;
        private readonly IServiceProviderAppService _serviceProviderAppService;

        public TicketController(ILogger<TicketController> logger, ITicketAppService ticketAppService, ITicketStatusAppService ticketStatusAppService, ITicketTypeAppService ticketTypeAppService, IServiceProviderAppService serviceProviderAppService)
        {
            _logger = logger;
            _ticketAppService = ticketAppService;
            _ticketStatusAppService = ticketStatusAppService;
            _ticketTypeAppService = ticketTypeAppService;
            _serviceProviderAppService = serviceProviderAppService;
        }

        public IActionResult Index(Guid? serviceProviderId, Guid? ticketTypeId, Guid? ticketStatusId)
        {
            LoadFilters();

            if (serviceProviderId == null && ticketTypeId == null && ticketStatusId == null)
                return View(_ticketAppService.GetAll());
            else
                return View(_ticketAppService.Find(x => x.TicketTypeId == ticketTypeId && x.TicketStatusId == ticketStatusId));
        }

        [HttpGet]
        [Route("details-ticket/{id:guid}")]
        public IActionResult Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var ticketViewModel = _ticketAppService.GetById(id.Value);

            if (ticketViewModel == null)
            {
                return NotFound();
            }

            return View(ticketViewModel);
        }

        [HttpGet]
        [Route("create-ticket/")]
        public IActionResult Create()
        {
            ViewBag.TicketStatus = _ticketStatusAppService.GetAll();
            ViewBag.TicketTypes = _ticketTypeAppService.GetAll();
            ViewBag.ServiceProviders = _serviceProviderAppService.GetAll();

            return View(new TicketViewModel());
        }

        [HttpGet]
        [Route("edit-ticket/{id:guid}")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            ViewBag.TicketStatus = _ticketStatusAppService.GetAll();
            ViewBag.TicketTypes = _ticketTypeAppService.GetAll();
            ViewBag.ServiceProviders = _serviceProviderAppService.GetAll();

            var ticketViewModel = _ticketAppService.GetById(id.Value);

            if (ticketViewModel == null)
            {
                return NotFound();
            }

            return View(ticketViewModel);
        }

        [HttpGet]
        [Route("delete-ticket/{id:guid}")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var ticketViewModel = _ticketAppService.GetById(id.Value);

            if (ticketViewModel == null)
            {
                return NotFound();
            }

            return View(ticketViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create-ticket/")]
        public IActionResult Create(TicketViewModel ticketViewModel)
        {
            if (!ModelState.IsValid) return View(ticketViewModel);

            _ticketAppService.Add(ticketViewModel);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit-ticket/{id:guid}")]
        public IActionResult Edit(TicketViewModel ticketViewModel)
        {
            if (!ModelState.IsValid) return View(ticketViewModel);

            _ticketAppService.Update(ticketViewModel);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("delete-ticket/{id:guid}")]
        public IActionResult Delete(TicketViewModel ticketViewModel)
        {
            _ticketAppService.Remove(ticketViewModel.Id);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private void LoadFilters()
        {
            ViewBag.TicketStatus = _ticketStatusAppService.GetAll();
            ViewBag.TicketTypes = _ticketTypeAppService.GetAll();
            ViewBag.ServiceProviders = _serviceProviderAppService.GetAll();
        }
    }
}

src/CoollabTech.UI.Web/Views/Home/Edit.cshtml
@model CoollabTech.Application.ViewModels.CitizenViewModel

@{
    ViewData["Title"] = "Edit";
}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="" asp-controller="home" asp-action="index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-action="Users">Usuários</a></li>
            <li class="breadcrumb-item active" aria-current="#">Editar Usuário</li>
        </ol>
    </nav>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div hidden class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Document" class="control-label"></label>
                <input asp-for="Document" class="form-control" />
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success btn-main" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CoollabTech.UI.Web/Views/Home/Index.cshtml
<div class="container dash">
    <div class="shadow-none p-3 bg-light rounded">Usuários</div>
    <div class="row mb-5">
        <div class="col-3">            
            <a class="btn btn-primary btn-main" asp-area="" asp-controller="Home" asp-action="Users">Listar</a>
        </div>

    </div>
    <div class="shadow-none p-3 bg-light rounded">Chamados</div>
    <div class="row">
        <div class="col-3">            
            <a class="btn btn-primary btn-main" asp-area="" asp-controller="Ticket" asp-action="create">Cadastrar</a>
        </div>
        <div class="col-3">            
            <a class="btn btn-primary btn-main" asp-area="" asp-controller="Ticket" asp-action="index">Listar</a>
        </div>
        <!-- div class="col-3">
          <a href="ticket?action=open-list-page" class="btn btn-main">Alterar</a>
        </div>
        <div class="col-3">
          <a href="ticket?action=open-list-page" class="btn btn-main">Remover</a>
        </div> -->
    </div>
</div>

src/CoollabTech.UI.Web/Views/Home/Users.cshtml
@model IEnumerable<CoollabTech.Application.ViewModels.CitizenViewModel>

@{
    ViewData["Title"] = "Usuários";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="home" asp-action="index">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="#">Usuários</li>
    </ol>
</nav>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NickName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NickName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Document)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>               
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">
                        Editar
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>